### ISSUE TITLE
Mods table action dropdown closes on its own on resource load

### ISSUE THREAD

**Issue by fungairino** [pixiebrix/pixiebrix-extension#8458]
## Describe the bug

The dropdown for mod actions in the extension console closes by itself if you open it right after refreshing.

See: https://pixiebrix.slack.com/archives/C0436P48QHY/p1715633444678499

## To Reproduce

See: https://www.loom.com/share/f638a468835044c095bcb598c6e3d7e5

## Actual behavior

The dropdown if opened, will not close without user input.

## Expected behavior

The dropdown if opened, will not close without user input.

## Screenshots/Loom

See: https://www.loom.com/share/f638a468835044c095bcb598c6e3d7e5

## Additional context

Related code pointers: 

ListView
https://github.com/pixiebrix/pixiebrix-extension/blob/78fe96dacffee27c9b9667eae10ebcd81c3ceab6/src/extensionConsole/pages/mods/listView/ListView.tsx#L30

ModsPageLayout
https://github.com/pixiebrix/pixiebrix-extension/blob/563e7e48fc5766302aae715c9be8b04866366759/src/extensionConsole/pages/mods/ModsPageLayout.tsx#L130

**Comment by twschiller** [comment]
See Slack re-renders likely occur when marketplace query and/or registry items resolve

**Comment by fungairino** [comment]
Here is a end-to-end test report showing flaky tests due to this behavior: 
https://github.com/pixiebrix/pixiebrix-extension/actions/runs/9881381380/job/27292047996

**Comment by fungairino** [comment]
See:
https://github.com/pixiebrix/pixiebrix-extension/blob/4deb84ec5045506e9dd7dbc7a371e8e5a2923e71/src/mods/useModViewItems.tsx#L178-L180

**Comment by twschiller** [comment]
Will likely want to solve root cause as part of https://www.notion.so/pixiebrix/Extension-Console-Mod-Screen-shift-left-conversion-to-common-mod-shape-d457621fc83d495bbeb135cbd3977ee6?pvs=4

**Comment by twschiller** [comment]
@BLoe @fungairino does this problem exist on main anymore? I didn't see it locally

**Comment by BLoe** [comment]
Yes, this should be fixed with my recent mods page refactor PR.

**Comment by fungairino** [comment]
This was not actually fixed. I'm not sure what refactor Ben was referring to.

**Comment by twschiller** [comment]
The PR he was referring to was this one, which restructured mod data: https://github.com/pixiebrix/pixiebrix-extension/pull/9040

If/when we look into this issue, we might also look to improve the UI. Right now all the mods flash as "Unavailable" until the mod definitions load to determine if the user still has access to definitions of activated mods
